### ISSUE TITLE
Calling e-internationalisation independently?

### ISSUE THREAD

**Issue by fsasaki** [freme-project/e-Internationalization#26]
Is it posible to call e-internationalisation independently? That is, without calling e-Entity etc. The use case is that one may want to convert XML or other content to a NIF representation and process this also outside of specific FREME services.

**Comment by jnehring** [comment]
One can use the Java API exposed by the e-Internationalization repository to do so. It is possible, but not documented. There are some unit tests that show how to do it.

**Comment by fsasaki** [comment]
Understand, but for the freme services to make this useful we would need a rest api call. Let's keep this open and give it a thought.

**Comment by jnehring** [comment]
Ah no I see what you mean. I misunderstood you in my first answer.

We could implement an anything to NIF converter e-Service. This REST endpoint can convert plaintext and all formats accepted by e-Internationalization to NIF. We talked about this because on the Lider datathon people asked me for this functionality.

**Comment by fsasaki** [comment]
+1 one, good idea.

2015-10-29 22:15 GMT+09:00 Jan Nehring <notifications@github.com>:

**Comment by jnehring** [comment]
This is possible through our anything to NIF converter: http://api.freme-project.eu/doc/current/api-doc/full.html#!/Toolbox/post_toolbox_nif_converter
